### PR TITLE
Fix recent regressions

### LINKED ISSUE #64: Some commits caused bad indentation and broke the tests
So if I checkout bb602e1 the tests for indentation breaks badly because it indents things badly, which is great and all that we now have tests. We just need to get feedback with travis (which was being worked on) to get a flow of this.

But what's worse is that 4ac7b5a seems to break the indentation that the tests does so nothing happens at all.

My plan for the moment is to add a test which contains broken indentation so we can have a test that that `(should-not)` match the input file to detect this kind of broken.

I'm not sure what bb602e1 was supposed to do overall since it touched many places. But I find some things that I would consider regressions straight of by reading that commit.

One example, `nix-is-comment-p` was added which is great and all and get the 3rd element from the result of `syntax-ppss`:
https://github.com/NixOS/nix-mode/commit/bb602e160fa5bb8ae15b113ebf308f0fb30b3aa9#diff-e75a5e47fe55dc4b6e12cf1e4c7a42adR521

And that function is then used here:
https://github.com/NixOS/nix-mode/commit/bb602e160fa5bb8ae15b113ebf308f0fb30b3aa9#diff-e75a5e47fe55dc4b6e12cf1e4c7a42adL528

Where the original code read the 3th element from the result of `syntax-ppss`.

Changing 3 to 4 there didn't repair the tests though.

@matthewbauer

### PR DESCRIPTION
**Pull request by etu**
I dropped the wrong branch when I cleaned out stuff in my fork... :-)

But I rebased this on master and it's the same as #67 in all other ways.

This also fixes #64.

It fixes some (for me) quite serious bugs in master.

### CODE REVIEW

**Comment by etu** [comment]
I will provide some examples of why this is a serious problems:

#### First problem: The tests doesn't run properly
The tests aren't even tested, this can be proved by going into a test and change the indentation to be broken. Then run the test. If you do this in any indentation related test that I've added on master you will see that it passed. And if you apply the change from a30e883 and run the test again you will see that it failed (not only because of the changed file though, but that's the second problem).

But to prevent this in the future I've added a testcase with broken indentation that requires it to be indented and then have a check that looks that the buffer is not the same as the file instead of the reverse. This way we can know if it breaks the same way again.

#### Second problem: The tests indent badly
This can be demonstrated by first fixing the first issue, just by dropping a line and then removing running the tests and look at the following output:

Example:
```nix
let
  x = [
    (let y = 1; in y)
    { foo = 1; }
    [ 1 2 3 ]
    x
  ];
in x
```
becomes
```nix
let
  x = [
    (let y = 1; in y)
      { foo = 1; }
        [ 1 2 3 ]
          x
  ];
in x
```

and
```nix
let
  x = [
    (let y = 1; in y)
    { foo = 1; }
    [ 1 2 3 ]
    x
  ];
in x
```
becomes
```nix
let
  x = [
    (let y = 1; in y)
      { foo = 1; }
        [ 1 2 3 ]
          x
  ];
in x
```

And that was fixed in 1f922d7. I haven't reflected at all over if the regex is correct or not. I just grabbed the old one that was in use before the refactoring and cleanups. So it worked before with the one and seems to work now as well with 1f922d7.

So at the moment it's to me clearly broken.

**Comment by etu** [comment]
cc @grahamc @matthewbauer

**Comment by wedens** [comment]
There are some problems with handling empty lists and sets:
```nix
{
}
```
is being indented as
```
{
  }
```
and
```nix
{
x = [
];
}
````
as
```nix
{
  x = [
    ];
}
```

As soon as there is at least 1 element, it seems to work fine.

**Comment by wedens** [comment]
Another case:
```nix
{
  a = {
    x1="abc";
  };
b = {
  x2 = 1;
};
}
```
is just left as is on attempt to indent. But if you add spaces to ` x1 = "abc"; `, it'll indent correctly.

**Comment by etu** [comment]
@wedens I have just tested these cases in some fixes before this PR is scoped for fixing. And the same issues seems to have existed back in 6445ebf as well.

So it would be nice if you could put them as a separate issue so we can track it separately and fix a bunch of issues at the time :)

**Comment by wedens** [comment]
@etu Ok. I've created a new issue https://github.com/NixOS/nix-mode/issues/69.
I'm not sure about #63, but IIRC there were no issues with empty lists/sets in #61.

**Comment by grahamc** [comment]
@matthewbauer can you merge? some melpa users are getting the one with regressions.

**Comment by grahamc** [comment]
```nix
{
  a = [
    ];
}
```

was a problem before this PR.

**Comment by matthewbauer** [comment]
Yeah sorry for the delay

**Comment by grahamc** [comment]
Thank you! Do you know if we can get this update to 18.09 too, or are they doomed until19.03?

**Pull request merged**
