### PR TITLE
Ert indent testing

### PR DESCRIPTION
**Pull request by etu**
So I've done some work on writing ert tests for indentation in nix-mode using nix-indent-line as indentation function.

Ignore the first commit 98426b9 since it's part of the PR #61 which kinda makes the indentation a lot better (imo).

But this PR depends on that change for this test to pass so I based this branch on those changes.

Tests run as easily as:
```
nix-shell --pure --run "make test" -p gnumake emacs
```

And to see that the test works for the test case I've added, just open the file `list-contents.nix` and mess something up in there (like de-indent something that should be indented) and run the test again. Then the indentation mode will fix the mess and compare it to the file -- which will fail.

And, more tests are needed. Much more tests. For different cases. I will grab a few of the ones from #60 because they are quite small and good.

This work is heavily inspired by how php-mode does it's indentation testing, but quite much simpler since php has different indentation standards which we kinda can ignore here.

cc @grahamc @matthewbauer

### CODE REVIEW

**Comment by matthewbauer** [comment]
Thanks a lot! I want to get travis working but don't have permissions to add it on this repo.

**Comment by etu** [comment]
@matthewbauer That would be great to have, do you know who to talk to to set that up?

**Comment by grahamc** [comment]
I'm working on getting this Travis added.

**Comment by grahamc** [comment]
Travis is set up now.

**Pull request merged**
