### PR TITLE
Transient interface for Nix flake commands

### PR DESCRIPTION
**Pull request by akirak**
This is an attempt to implement #104.

I don't know if you will like this, but it has helped me with building flakes, so I will propose a draft PR.

### CODE REVIEW

**Comment by matthewbauer** [comment]
Looks good to me so far!

**Comment by akirak** [comment]
I squashed commits and added transient to the dependency list in flake.nix.

CI fails, but it is probably due to an issue with install-nix-action, which may be soon fixed by https://github.com/cachix/install-nix-action/pull/105. Please wait for a while.

**Comment by akirak** [comment]
@domenkozar Thank you. It's working!

**Comment by akirak** [comment]
Thank you so much for merging this PR!

**Pull request merged**
